# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}. Each bullet point must be provided with its sources as urls to reach the information.

research_task:
  description: >
    Search for the latest developments in artificial intelligence using the websites below:
    - The Verge (https://www.theverge.com/ai-artificial-intelligence/)
    - Forbes (https://www.forbes.com/ai/)
    - MIT Technology Review (https://www.technologyreview.com/c/ai/)
    - Wired – AI: https://www.wired.com/tag/artificial-intelligence/
    - TechCrunch – AI: https://techcrunch.com/tag/artificial-intelligence/


    Your goal is to try to collect **3-5 relevant and recent articles**. Focus on topics related to the US, Big Tech (GAFAM), and major research breakthroughs.

    In any case, i want you to find information about the subjects and give them. So if you need, you can look for other sources from other website.
    Do **not summarize** or rephrase the content — just extract the **raw data**.

  expected_output: >
    A list of 3-5 items max, each containing:
    - Article title
    - Full original excerpt or relevant section of the article (up to 2 paragraphs)
    - Name of the source (e.g., Forbes)
    - Article URL (use homepage if specific article link is unavailable)


reporting_task:
  description: >
    Based on the raw content collected by the Searcher agent, create a polished and structured newsletter section for each topic.

    Expand on the information to make it clear, insightful, and engaging for readers. Avoid copying the content — instead, summarize and explain
    using your own words. Summarize of 50 words max.

    Prioritize clarity, conciseness, and relevance. Emphasize developments from the US, Big Tech (GAFAM), and research institutions.

    You have to put a link for the source.

  expected_output: >
    5 articles max, each including:
    - A clear and catchy title.You have to include 2 emojis
    - 1-2 short paragraphs explaining the topic
    - Mention of the source (e.g., [Forbes](https://...))
    - Attribution of any original quote if used
