# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}. Each bullet point must be provided with its sources as urls to reach the information.

research_task:
  description: >
    Conduct thorough research about AI across the websites provided. Do not hallucinate or fabricate any information.
    - Forbes (https://www.forbes.com/ai/ )
    Priotize relevant information given the current date is 21/03/2025.
  expected_output: >
    5 Bulletpoints representing the most relevant developments retrieved from the various news outlets. Include a summary of 
    each development and include detailed sources, links and citations so that the information can be verified.

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
    Source
    - Forbes (https://www.forbes.com/ai/ )
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'. Include detailed sources, links and citations so that the information can be verified.
